### ISSUE TITLE
Crash after first launch

### ISSUE THREAD

**Issue by dustojnikhummer** [mrousavy/ImgurSniper#7]
Launching from icon
http://imgur.com/a/n0k7S and saying "Yes" to report.

**Comment by mrousavy** [comment]
Please test with the newest Version.

If the Problem still happens, continue reading:
Apparently this Issue occurs, because ImgurSniper can't find the "My Pictures" Path. To fix this, you have to adjust the config File manually, until I fix this.

It's in the config.json, when you open config.json with a text Editor, it may look like this:
`{"LastChecked":"2017-03-12T19:13:10.4733423+01:00","CurrentCommits":346,"AllMonitors":true,"ImgurAfterSnipe":true,"IsInContextMenu":true,"MagnifyingGlassEnabled":true,"OpenAfterUpload":true,"RunOnBoot":true,"SaveImages":false,"UsePNG":true,"UsePrint":false,"UpdateAvailable":false,"AutoUpdate":true,"Language":"en","SaveImagesPath":"C:\Users\Marc\Pictures\ImgurSniper Images","ShortcutKey":67}`

As you can see, deep in the spaghetti there is an Attribute `SaveImagesPath `which has the value
`"C:\Users\Marc\Pictures\ImgurSniper Images"`
for me.
Change this to an actual Directory, and everything works.

**Comment by mrousavy** [comment]
Fixed in newest Version, if not, adjust Config manually in `C:\Users\[UserName]\Documents\ImgurSniper` with any Text Editor (It's the `SaveImagesPath` Attribute)
